import type { Metadata } from "next";
import { Noto_Serif_Bengali} from "next/font/google";
import "./globals.css";
import ProductLink from "@/components/ProductLink";
import Navbar from "@/components/Navbar";
const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin","bengali"],
});


export const metadata: Metadata = {
  title: "Bazar-Dor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme='light'
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <Navbar/>

  <ProductLink/>

        {children}
        
        <p>Footer</p>
        
        </body>
    </html>
  );
}
